Info<< "Computing CW0\n" << endl;
volScalarField CW0 ("CW0", (24/Reloc0+4*pow(Reloc0,-0.333)));

Info<< "Computing CW1\n" << endl;
volScalarField CW1 ("CW1", (24/Reloc1+4*pow(Reloc1,-0.333)));

Info<< "Computing CW2\n" << endl;
volScalarField CW2 ("CW2", (24/Reloc2+4*pow(Reloc2,-0.333)));

Info<< "Computing CW3\n" << endl;
volScalarField CW3 ("CW3", (24/Reloc3+4*pow(Reloc3,-0.333)));

Info<< "Computing CW4\n" << endl;
volScalarField CW4 ("CW4", (24/Reloc4+4*pow(Reloc4,-0.333)));

Info<< "Computing CW5\n" << endl;
volScalarField CW5 ("CW5", (24/Reloc5+4*pow(Reloc5,-0.333)));

Info<< "Computing CW6\n" << endl;
volScalarField CW6 ("CW6", (24/Reloc6+4*pow(Reloc6,-0.333)));

Info<< "Computing CW7\n" << endl;
volScalarField CW7 ("CW7", (24/Reloc7+4*pow(Reloc7,-0.333)));

Info<< "Computing CW8\n" << endl;
volScalarField CW8 ("CW8", (24/Reloc8+4*pow(Reloc8,-0.333)));

Info<< "Computing CW9\n" << endl;
volScalarField CW9 ("CW9", (24/Reloc9+4*pow(Reloc9,-0.333)));

