Info<< "Reading Schmidt number 0\n" << endl;
dimensionedScalar Sc0
(
    "Sc0",
    dropletProperties.lookup("Sc0")
);

Info<< "Reading Schmidt number 1\n" << endl;
dimensionedScalar Sc1
(
    "Sc1",
    dropletProperties.lookup("Sc1")
);

Info<< "Reading Schmidt number 2\n" << endl;
dimensionedScalar Sc2
(
    "Sc2",
    dropletProperties.lookup("Sc2")
);

Info<< "Reading Schmidt number 3\n" << endl;
dimensionedScalar Sc3
(
    "Sc3",
    dropletProperties.lookup("Sc3")
);

Info<< "Reading Schmidt number 4\n" << endl;
dimensionedScalar Sc4
(
    "Sc4",
    dropletProperties.lookup("Sc4")
);

Info<< "Reading Schmidt number 5\n" << endl;
dimensionedScalar Sc5
(
    "Sc5",
    dropletProperties.lookup("Sc5")
);

Info<< "Reading Schmidt number 6\n" << endl;
dimensionedScalar Sc6
(
    "Sc6",
    dropletProperties.lookup("Sc6")
);

Info<< "Reading Schmidt number 7\n" << endl;
dimensionedScalar Sc7
(
    "Sc7",
    dropletProperties.lookup("Sc7")
);

Info<< "Reading Schmidt number 8\n" << endl;
dimensionedScalar Sc8
(
    "Sc8",
    dropletProperties.lookup("Sc8")
);

Info<< "Reading Schmidt number 9\n" << endl;
dimensionedScalar Sc9
(
    "Sc9",
    dropletProperties.lookup("Sc9")
);
