Info<< "Reading droplet diameter 0\n" << endl;
dimensionedScalar dW0
(
    "dW0",
    dropletProperties.lookup("dW0")
);

Info<< "Reading droplet diameter 1\n" << endl;
dimensionedScalar dW1
(
    "dW1",
    dropletProperties.lookup("dW1")
);

Info<< "Reading droplet diameter 2\n" << endl;
dimensionedScalar dW2
(
    "dW2",
    dropletProperties.lookup("dW2")
);

Info<< "Reading droplet diameter 3\n" << endl;
dimensionedScalar dW3
(
    "dW3",
    dropletProperties.lookup("dW3")
);

Info<< "Reading droplet diameter 4\n" << endl;
dimensionedScalar dW4
(
    "dW4",
    dropletProperties.lookup("dW4")
);

Info<< "Reading droplet diameter 5\n" << endl;
dimensionedScalar dW5
(
    "dW5",
    dropletProperties.lookup("dW5")
);

Info<< "Reading droplet diameter 6\n" << endl;
dimensionedScalar dW6
(
    "dW6",
    dropletProperties.lookup("dW6")
);

Info<< "Reading droplet diameter 7\n" << endl;
dimensionedScalar dW7
(
    "dW7",
    dropletProperties.lookup("dW7")
);

Info<< "Reading droplet diameter 8\n" << endl;
dimensionedScalar dW8
(
    "dW8",
    dropletProperties.lookup("dW8")
);

Info<< "Reading droplet diameter 9\n" << endl;
dimensionedScalar dW9
(
    "dW9",
    dropletProperties.lookup("dW9")
);

