Info<< "Computing relaxation time 0\n" << endl;
volScalarField relt0 ("relt0",(CW0*rhoW*pow(dW0,2)/(18*mu)));

Info<< "Computing relaxation time 1\n" << endl;
volScalarField relt1 ("relt1",(CW1*rhoW*pow(dW1,2)/(18*mu)));

Info<< "Computing relaxation time 2\n" << endl;
volScalarField relt2 ("relt2",(CW2*rhoW*pow(dW2,2)/(18*mu)));

Info<< "Computing relaxation time 3\n" << endl;
volScalarField relt3 ("relt3",(CW3*rhoW*pow(dW3,2)/(18*mu)));

Info<< "Computing relaxation time 4\n" << endl;
volScalarField relt4 ("relt4",(CW0*rhoW*pow(dW4,2)/(18*mu)));

Info<< "Computing relaxation time 5\n" << endl;
volScalarField relt5 ("relt5",(CW5*rhoW*pow(dW5,2)/(18*mu)));

Info<< "Computing relaxation time 6\n" << endl;
volScalarField relt6 ("relt6",(CW6*rhoW*pow(dW6,2)/(18*mu)));

Info<< "Computing relaxation time 7\n" << endl;
volScalarField relt7 ("relt7",(CW7*rhoW*pow(dW7,2)/(18*mu)));

Info<< "Computing relaxation time 8\n" << endl;
volScalarField relt8 ("relt8",(CW8*rhoW*pow(dW8,2)/(18*mu)));

Info<< "Computing relaxation time 9\n" << endl;
volScalarField relt9 ("relt9",(CW9*rhoW*pow(dW9,2)/(18*mu)));


