/////////////////////////////////////////////////////////////
Info<< "Reading field W0\n" << endl;
volScalarField W0
(
    IOobject
    (
        "W0",
        runTime.timeName(),
        mesh,
        IOobject::MUST_READ,
        IOobject::AUTO_WRITE
    ),
    mesh
);
/////////////////////////////////////////////////////////////
Info<< "Reading field W1\n" << endl;
volScalarField W1
(
    IOobject
    (
        "W1",
        runTime.timeName(),
        mesh,
        IOobject::MUST_READ,
        IOobject::AUTO_WRITE
    ),
    mesh
);
/////////////////////////////////////////////////////////////
Info<< "Reading field W2\n" << endl;
volScalarField W2
(
    IOobject
    (
        "W2",
        runTime.timeName(),
        mesh,
        IOobject::MUST_READ,
        IOobject::AUTO_WRITE
    ),
    mesh
);
/////////////////////////////////////////////////////////////
Info<< "Reading field W3\n" << endl;
volScalarField W3
(
    IOobject
    (
        "W3",
        runTime.timeName(),
        mesh,
        IOobject::MUST_READ,
        IOobject::AUTO_WRITE
    ),
    mesh
);
/////////////////////////////////////////////////////////////
Info<< "Reading field W4\n" << endl;
volScalarField W4
(
    IOobject
    (
        "W4",
        runTime.timeName(),
        mesh,
        IOobject::MUST_READ,
        IOobject::AUTO_WRITE
    ),
    mesh
);
/////////////////////////////////////////////////////////////
Info<< "Reading field W5\n" << endl;
volScalarField W5
(
    IOobject
    (
        "W5",
        runTime.timeName(),
        mesh,
        IOobject::MUST_READ,
        IOobject::AUTO_WRITE
    ),
    mesh
);
/////////////////////////////////////////////////////////////
Info<< "Reading field W6\n" << endl;
volScalarField W6
(
    IOobject
    (
        "W6",
        runTime.timeName(),
        mesh,
        IOobject::MUST_READ,
        IOobject::AUTO_WRITE
    ),
    mesh
);
/////////////////////////////////////////////////////////////
Info<< "Reading field W7\n" << endl;
volScalarField W7
(
    IOobject
    (
        "W7",
        runTime.timeName(),
        mesh,
        IOobject::MUST_READ,
        IOobject::AUTO_WRITE
    ),
    mesh
);
/////////////////////////////////////////////////////////////
Info<< "Reading field W8\n" << endl;
volScalarField W8
(
    IOobject
    (
        "W8",
        runTime.timeName(),
        mesh,
        IOobject::MUST_READ,
        IOobject::AUTO_WRITE
    ),
    mesh
);
/////////////////////////////////////////////////////////////
Info<< "Reading field W9\n" << endl;
volScalarField W9
(
    IOobject
    (
        "W9",
        runTime.timeName(),
        mesh,
        IOobject::MUST_READ,
        IOobject::AUTO_WRITE
    ),
    mesh
);
/////////////////////////////////////////////////////////////
